### ISSUE TITLE
FEATURE REQUEST - Traefik Google OAuth forward authentication for SSO

### ISSUE THREAD

**Issue by qazero** [Cloudbox/Cloudbox#242]
Any chance you could integrate the following features into Cloudbox?

https://github.com/thomseddon/traefik-forward-auth
https://github.com/daghaian/nzbthrottle

**Comment by danjames92** [comment]
1. What purpose would using Traefik over nginx serve? Looking for a use case.

2. Nzbthrottle is already a part of cloudbox. Please update your Cloudbox install and run the following...

`sudo ansible-playbook cloudbox.yml --tags nzbthrottle`

**Comment by desimaniac** [comment]
NZBThrottle is already included, as is mentioned above, just no docs for it yet.

Oauth thing ill look into..

**Comment by onelesd** [comment]
Take a look at [pusher/oauth2_proxy](https://github.com/pusher/oauth2_proxy#configuring-for-use-with-the-nginx-auth_request-directive). There is an nginx example leveraging the auth_request module (which is in the base nginx image that jwilder/nginx-proxy is based on).

**Comment by desimaniac** [comment]
Tried to use this, but had no luck: https://github.com/telcom/nginx-proxy-google-oauth

**Comment by onelesd** [comment]
The LUA-based solutions won't work because LUA is not supported in the base nginx image. 

`nginx-proxy` is based on `nginx`, so we'd need to fork `nginx-proxy` to get LUA working.

The auth_request module however is included and should work for `oauth2_proxy`.

**Comment by desimaniac** [comment]
That linked project above was built on top of jwilder/nginx-proxy's image.

**Comment by desimaniac** [comment]
Maybe we can add this along with the existing nginx-proxy image:

See:
https://github.com/packetfield/infra-core/blob/d1814b30eedc9c2b89676ee4a3966da0bb682309/ansible/roles/gocd/templates/docker-compose.yml
https://github.com/initab/techdaybyinit/blob/a6980e766ff6d4527087feb2eb3d6cc8ff13b29f/docker-compose.yml

I’d have to look into this more. If someone to give it a shot I a separate branch on a fork, that would be fine too.

**Comment by onelesd** [comment]
Nice find! That looks like it should slide in nicely. I'll play around with it if I have time this week.

**Comment by desimaniac** [comment]
You can find me on [discord](https://discord.io/cloudbox).

**Comment by LooseSeal2** [comment]
I'm working on a refactor of cloudbox to eliminate some of the repeated code when deploying containers. I'm also adding traefik and oauth to it. It's currently a WIP, check the `refactor` branch on my fork. This is more for my use-case, but with some tweaks could be merged in.

Few things I did:
Made library paths configurable
Made subdomains for apps configurable
refactored repeated code into _core and _docker task files.
renamed plexpy -> tautulli
renamed nzbhydra2 -> nzbhydra
renamed unionfs -> mergerfs
Made app auth per app, instead of using same creds as linux user account...
Made some static directories configurable.
By default plex, emby, jellyfin, and ombi don't use oauth.
Added Jellyfin
Added LazyLibrarian
Changed Arr and other apps from using 'suitarr' to use LSIO images.
Drop suitarr in favor of regular images.
dropped cloudbox specific images in favor of LSIO
Changed cloudflare DNS to CNames and proxied by default. CNames are preferred over A records for subdomains that point to same IP. CF uses CName flattening, so A records are just more maintenance if IP changes.
/opt/appname, I changed them to /opt/{{role_name}} (with the exception of a few plex addons)

What's left:
Add a check that only adds traefik labels if using traefik
Add a check to only add oauth label if using oauth
Refactor the rest of the apps to use shared tasks.
Make darkerr work with traefik?
Make CF record type (auto)configurable (For those with feederbox and mediabox)
Make image configurable in adv_settings

What could be done if wanted:

Add option to expose ports and remap the external ones via prompt
Change subdomain via prompt overriding the settings file.
Drop legacy migration tasks
eliminate Arr4k roles and instead add prompt to change the 'role_name', which would essentially do the same thing now.

Can jump on discord and discuss...

**Comment by desimaniac** [comment]
Sure

**Comment by JigSawFr** [comment]
Could be a great addition to avoid setting multiple login/password with different interface.
One login, multiple access :)

**Comment by JigSawFr** [comment]
@Fma965 just written a wiki page on this topic https://github.com/Cloudbox/Cloudbox/wiki/Organizr-Auth-for-Nginx-Proxy-Apps
Thank you !

**Comment by Fma965** [comment]
Thanks although some credit would be nice. It took me a little while to figure this out.

**Comment by Fma965** [comment]
Your also missing an entire section that is required.

**Comment by Fma965** [comment]
https://cyanlabs.net/kb/organizr-auth-on-cloudbox/ full guide.

**Comment by JigSawFr** [comment]
@Fma965 thank you i didn't noticed it before in discord, so that's why I've written a page directly in FAQ

**Comment by Fma965** [comment]
@JigSawFr  no worries although there is no need for this line in each proxy config just put it in the default

```
## Auth block - Organizr ##
location ~ ^/auth-(.*) {
    ## Has to be local ip or local DNS name
    proxy_pass http://organizr:80/api/?v1/auth&group=$1;
    proxy_pass_request_body off;
    proxy_set_header Content-Length "";

}
```

**Comment by saltydk** [comment]
We're going to have Traefik in the develop branch in the near future and users will be able to deploy whatever Traefik SSO they like using the inventory variables. So I am closing this.
