### ISSUE TITLE
preinstall fails if rclone is missing

### ISSUE THREAD

**Issue by LooseSeal2** [Cloudbox/Cloudbox#313]
**Describe the bug**
A new clean install, running the preinstall tag should install rclone, but it fails because a var isn't set. Fails at "Build URL | Set vars for current version"

**To Reproduce**
1. Clean install, do not install rclone
2. Do not run dep installer
3. Just run preinstall tag

**Expected behavior**
It installs rclone, needs to check if var exists

**System Information**

 - Cloudbox Version: Develop (latest)
 - Operating System: Ubuntu Server 18.04 LTS

**Comment by desimaniac** [comment]
Preinstall installs `Rclone`. 
In the `Rclone` role, the `Build URL` task file runs the `Build URL | Set vars for current version` task. 

Would need to see log on why it's failing (ie `-vvv`).

If i had to guess, it's probably because it ran so many times that it rate limited your access to GitHub. Although, it should have fallen back to a backup Rclone install version.
