### ISSUE TITLE
Encryption recommendation as default.

### ISSUE THREAD

**Issue by C42EFF4Lbb54dwg** [Cloudbox/Cloudbox#393]
It is no secret that you can utilise Google Search to find video content stored on, i.e., Google Drive ([see here](https://www.reddit.com/r/YouShouldKnow/comments/carxeg/ysk_you_can_search_movies_on_google_by_typing/)) and requesting removal of content is not a difficult endeavour [(see here)](https://support.google.com/legal/troubleshooter/1114905?hl=en). The consequences of being targeted include a shut down of your drive [(see here)](https://support.google.com/accounts/thread/21194028?hl=en), and could result in civil action against the owner of the drive. 

When hosting Cloudbox on a remote dedicated server (i.e., Hetzner), it should be the default recommendation that steps are taken to protect the user. It is not difficult to setup a rclone crypt [(see here)](https://rclone.org/crypt/) to avoid the aforesaid and encrypting the home drive [(see here)](sudo adduser --encrypt-home <user>) where the rclone config is located, thus making it near impossible to retrieve the passwords to the encrypted rclone setup.

Unfortunately, it is incredibly difficult to setup a full disk encrypted setup on a dedicated remote server but not to do the above.

**Comment by saltydk** [comment]
Since there are trade-offs to making encryption of Google Drive default it will have to include useful benefits to tip the scale. The perceived benefit of Google not banning you amounts to speculation. As it has been debated on our discord multiple times, there are benefits for Google when we do not use encryption and as far as public searches those would only be relevant to anyone publicly sharing their files.

As far as encryption of GDrive the conventional wisdom is that Google doesn't care what you store there until someone outside of their company targets you, which they won't know to do if you do not share content with users you do not control. If you want to use encryption anyway that is your decision but I strongly doubt that we'll implement it as the default setup.

As far as system hardening goes that is always going to be relative to what kind of attack vectors you are expecting so making the default install encrypt anything is likely to cause issues with a large amount of users not used to dealing with the limitations this can create.

**Comment by chazlarson** [comment]
I noticed that when using Google to search for video files as described in that link, everything I found had sharing settings wide open, which is a choice made by the google drive account holder.

![image](https://user-images.githubusercontent.com/3865541/85026364-3300ca80-b13e-11ea-9a10-92829b15b038.png)
