### ISSUE TITLE
Fail2ban fail to start with clean lxc container

### ISSUE THREAD

**Issue by fensoft** [Cloudbox/Cloudbox#404]
**To Reproduce**
1. Install clean debian distrib in lxc: lxc-create -n cloudbox -t debian -- -r stretch
2. Attach to the root console: lxc-attach cloudbox
3. Install cloudbox as usual

fail2ban then fail to start because no /var/log/auth file was found. Maybe because we're not logged in through ssh.
To solve this, i've disabled sshd in /etc/fail2ban/jail.d/defaults-debian.conf

**Comment by saltydk** [comment]
I do not think we are nor are planning to support virtualized environments at this time and frankly your problem is not related to anything we handle either. You should take this to the fail2ban devs or maybe have a look here https://github.com/fail2ban/fail2ban/issues/1470 and see if you can find a way around this limitation.
