### ISSUE TITLE
Complex password in `accounts.yml` require quote wrapping.

### ISSUE THREAD

**Issue by risb0r** [Cloudbox/Cloudbox#431]
**Describe the bug**
A password that containers a `#` as the first character in `accounts.yml` require the password to be wrapped in quotes otherwise it will think the file is blank.

**To Reproduce**
1. Under User > pass in `accounts.yml` place a '#' as the first character of the password.
2. Attempt to update a container eg `sudo ansible-playbook cloudbox.yml --tags sonarr`
3. The update will fail and report the following error
`TASK [settings : Finish | Ensure that required values are not blank] *******************************************************************************************
Saturday 17 October 2020  22:07:06 +1100 (0:00:00.257)       0:01:07.871 ******
fatal: [localhost]: FAILED! => {
    "assertion": "\"\" | trim != \"\"",
    "changed": false,
    "evaluated_to": false,
    "msg": "'user' values in 'accounts.yml' cannot be blank"
}`

**Expected behavior**
Password to be accepted natively without quotes

**Logs**
`---
user:
  name: cloudbox
  pass: #xxx
  domain: xxx.xxx
  email: xxx@xxx.xxx
cloudflare:
  email: xxx@xxx
  api: 12345
plex:
  user: xxx@xxx.xxx
  pass: 12345
pushover:
  app_token:
  user_key:
  priority:
apprise:`

**System Information**

 - Cloudbox Version: [1.4.5, Master (latest)]
 - Operating System: [Ubuntu 18.04.5 LTS]
 - Linux Kernel: [4.15.0-118-generic]

**Additional context**
@chazlarson and @owine assisted with troubleshooting this on discord, thanks!!. Link below for reference;
https://discordapp.com/channels/381077432285003776/402867972236115968/766982923290935307

**Comment by Jericon** [comment]
I don't feel that this is a bug at all.  The YAML documentation specifically states that the '#' character needs to be escaped or quoted.

https://support.asg.com/mob/mvw/10_0/mv_ag/using_quotes_with_yaml_special_characters.htm

**Comment by saltydk** [comment]
I feel like it is easier just to have the wiki state which characters are allow and be done with it. As this seems like something that likely won't change with how ansible works. Not really up to making scripts that get around this since the problem can be fixed just by making a strong password without the problem characters.

Should anyone find a good solution to this particular problem feel free to leave a comment here or poke me on the Cloudbox Discord.

**Comment by Jericon** [comment]
The way I see it, this isn't a problem with ansible... or cloudbox.  It's simply good syntax.  Have a special character, quote it.  The same applies to MySQL's my.cnf files, but it's not listed as a bug or issue.  It's just understood, if you have a special character, quote it.  

I think the better solution would be to say on the wiki "use quotes in yaml" instead of saying that specific characters are not allowed.

**Comment by saltydk** [comment]
I don't disagree but you do have people that would put double quotes in their passwords and then we're back here :p
