### ISSUE TITLE
Sonarr import issues

### ISSUE THREAD

**Issue by Organikk** [Cloudbox/Cloudbox#69]
Hello again, getting various different import errors in Sonarr:

- No files found are eligible for import in /downloads/nzbget/completed/sonarr/example
- Episode Number 14 was unexpected considering the example.S05E13 folder name
- Invalid season or episode
- This show has individual episode mappings on TheXEM but the mapping for this episode has not been confirmed yet by their administrators. TheXEM needs manual input.
- Sample

Again, running stock Sonarr configured exactly as listed in the Wiki. The downloader used here is NZBGet. I feel like this is related to renaming or something but not sure. I believe the files are actually showing up fine in Plex, but they get stuck in the activity log in Sonarr.

**Update** Looks like it was NZBGet history. After purging that, Sonarr no longer had those import errors listed in the activity tab. I set KeepHistory to 0 for a while, until I realized Autoscan was no longer running. I set it to 1 day now so hopefully that solves all issues.

Side note: Is there a way to speed up the process of media being fully downloaded and then showing up in Plex? Seems to take quite a while before it shows up. I believe autoscan might be to blame there.

Thanks

**Comment by desimaniac** [comment]
Good catch.


Plex Autoscan config as a variable ` "SERVER_SCAN_DELAY":` that is set to `180` seconds by default. This allows multiple requests to scan the same season folder, within that time-frame, to be merged as one request to Plex. This is handy if you are downloading consecutive episodes of a show that are maybe spaced out by a min or two. 

However, you can lower that down so that they  show up faster in Plex.
